//
// Created by Lok on 17.11.2022.
//

#ifndef S21_CONTAINERS_SRC_CONTAINER_ADAPTOR_QUEUE_H_
#define S21_CONTAINERS_SRC_CONTAINER_ADAPTOR_QUEUE_H_

#endif //S21_CONTAINERS_SRC_CONTAINER_ADAPTOR_QUEUE_H_
